// Code generated by pigeon; DO NOT EDIT.

package parser

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"
)

func anyToSlice[T any](s any) []T {
	var ret []T
	for _, e := range s.([]any) {
		if e == nil {
			continue
		}
		ret = append(ret, e.(T))
	}

	return ret
}

var g = &grammar{
	rules: []*rule{
		{
			name: "Program",
			pos:  position{line: 18, col: 1, offset: 192},
			expr: &actionExpr{
				pos: position{line: 18, col: 12, offset: 203},
				run: (*parser).callonProgram1,
				expr: &seqExpr{
					pos: position{line: 18, col: 12, offset: 203},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 18, col: 12, offset: 203},
							label: "pkg",
							expr: &ruleRefExpr{
								pos:  position{line: 18, col: 16, offset: 207},
								name: "Package",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 18, col: 24, offset: 215},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 18, col: 26, offset: 217},
							label: "decls",
							expr: &zeroOrMoreExpr{
								pos: position{line: 18, col: 32, offset: 223},
								expr: &ruleRefExpr{
									pos:  position{line: 18, col: 33, offset: 224},
									name: "Declaration",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 18, col: 47, offset: 238},
							name: "EOF",
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "Package",
			pos:  position{line: 26, col: 1, offset: 354},
			expr: &actionExpr{
				pos: position{line: 26, col: 12, offset: 365},
				run: (*parser).callonPackage1,
				expr: &seqExpr{
					pos: position{line: 26, col: 12, offset: 365},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 26, col: 12, offset: 365},
							val:        "package",
							ignoreCase: false,
							want:       "\"package\"",
						},
						&ruleRefExpr{
							pos:  position{line: 26, col: 22, offset: 375},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 26, col: 24, offset: 377},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 26, col: 29, offset: 382},
								name: "Identifier",
							},
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "Declaration",
			pos:  position{line: 32, col: 1, offset: 454},
			expr: &ruleRefExpr{
				pos:  position{line: 32, col: 16, offset: 469},
				name: "FunctionDeclaration",
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "Type",
			pos:  position{line: 34, col: 1, offset: 490},
			expr: &choiceExpr{
				pos: position{line: 34, col: 9, offset: 498},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 34, col: 9, offset: 498},
						name: "Identifier",
					},
					&ruleRefExpr{
						pos:  position{line: 34, col: 22, offset: 511},
						name: "PointerType",
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "PointerType",
			pos:  position{line: 36, col: 1, offset: 524},
			expr: &actionExpr{
				pos: position{line: 36, col: 16, offset: 539},
				run: (*parser).callonPointerType1,
				expr: &seqExpr{
					pos: position{line: 36, col: 16, offset: 539},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 36, col: 16, offset: 539},
							val:        "*",
							ignoreCase: false,
							want:       "\"*\"",
						},
						&labeledExpr{
							pos:   position{line: 36, col: 20, offset: 543},
							label: "pointee",
							expr: &ruleRefExpr{
								pos:  position{line: 36, col: 28, offset: 551},
								name: "Type",
							},
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "Statement",
			pos:  position{line: 40, col: 1, offset: 612},
			expr: &choiceExpr{
				pos: position{line: 40, col: 14, offset: 625},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 40, col: 14, offset: 625},
						name: "VarStatement",
					},
					&ruleRefExpr{
						pos:  position{line: 40, col: 29, offset: 640},
						name: "PostfixStatement",
					},
					&ruleRefExpr{
						pos:  position{line: 40, col: 48, offset: 659},
						name: "ExprStatement",
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "VarStatement",
			pos:  position{line: 42, col: 1, offset: 674},
			expr: &actionExpr{
				pos: position{line: 42, col: 17, offset: 690},
				run: (*parser).callonVarStatement1,
				expr: &seqExpr{
					pos: position{line: 42, col: 17, offset: 690},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 42, col: 17, offset: 690},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 42, col: 19, offset: 692},
							val:        "var",
							ignoreCase: false,
							want:       "\"var\"",
						},
						&ruleRefExpr{
							pos:  position{line: 42, col: 25, offset: 698},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 42, col: 27, offset: 700},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 42, col: 32, offset: 705},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 42, col: 43, offset: 716},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 42, col: 45, offset: 718},
							label: "typ",
							expr: &zeroOrOneExpr{
								pos: position{line: 42, col: 49, offset: 722},
								expr: &ruleRefExpr{
									pos:  position{line: 42, col: 49, offset: 722},
									name: "Type",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 42, col: 55, offset: 728},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 42, col: 57, offset: 730},
							label: "exp",
							expr: &zeroOrOneExpr{
								pos: position{line: 42, col: 61, offset: 734},
								expr: &ruleRefExpr{
									pos:  position{line: 42, col: 61, offset: 734},
									name: "VarStatementExpr",
								},
							},
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "VarStatementExpr",
			pos:  position{line: 62, col: 1, offset: 1078},
			expr: &actionExpr{
				pos: position{line: 62, col: 21, offset: 1098},
				run: (*parser).callonVarStatementExpr1,
				expr: &seqExpr{
					pos: position{line: 62, col: 21, offset: 1098},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 62, col: 21, offset: 1098},
							val:        "=",
							ignoreCase: false,
							want:       "\"=\"",
						},
						&ruleRefExpr{
							pos:  position{line: 62, col: 25, offset: 1102},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 62, col: 27, offset: 1104},
							label: "exp",
							expr: &ruleRefExpr{
								pos:  position{line: 62, col: 31, offset: 1108},
								name: "Expr",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 62, col: 36, offset: 1113},
							name: "_",
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "ExprStatement",
			pos:  position{line: 66, col: 1, offset: 1145},
			expr: &actionExpr{
				pos: position{line: 66, col: 18, offset: 1162},
				run: (*parser).callonExprStatement1,
				expr: &seqExpr{
					pos: position{line: 66, col: 18, offset: 1162},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 66, col: 18, offset: 1162},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 66, col: 20, offset: 1164},
							label: "exp",
							expr: &ruleRefExpr{
								pos:  position{line: 66, col: 24, offset: 1168},
								name: "Expr",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 66, col: 29, offset: 1173},
							name: "_",
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "PostfixStatement",
			pos:  position{line: 70, col: 1, offset: 1226},
			expr: &actionExpr{
				pos: position{line: 70, col: 21, offset: 1246},
				run: (*parser).callonPostfixStatement1,
				expr: &seqExpr{
					pos: position{line: 70, col: 21, offset: 1246},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 70, col: 21, offset: 1246},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 70, col: 23, offset: 1248},
							label: "exp",
							expr: &ruleRefExpr{
								pos:  position{line: 70, col: 27, offset: 1252},
								name: "Expr",
							},
						},
						&labeledExpr{
							pos:   position{line: 70, col: 32, offset: 1257},
							label: "op",
							expr: &choiceExpr{
								pos: position{line: 70, col: 36, offset: 1261},
								alternatives: []any{
									&litMatcher{
										pos:        position{line: 70, col: 36, offset: 1261},
										val:        "++",
										ignoreCase: false,
										want:       "\"++\"",
									},
									&litMatcher{
										pos:        position{line: 70, col: 43, offset: 1268},
										val:        "--",
										ignoreCase: false,
										want:       "\"--\"",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 70, col: 49, offset: 1274},
							name: "_",
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "FunctionDeclaration",
			pos:  position{line: 74, col: 1, offset: 1363},
			expr: &actionExpr{
				pos: position{line: 74, col: 24, offset: 1386},
				run: (*parser).callonFunctionDeclaration1,
				expr: &seqExpr{
					pos: position{line: 74, col: 24, offset: 1386},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 74, col: 24, offset: 1386},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 74, col: 26, offset: 1388},
							val:        "func",
							ignoreCase: false,
							want:       "\"func\"",
						},
						&ruleRefExpr{
							pos:  position{line: 74, col: 33, offset: 1395},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 74, col: 35, offset: 1397},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 74, col: 40, offset: 1402},
								name: "Identifier",
							},
						},
						&litMatcher{
							pos:        position{line: 74, col: 51, offset: 1413},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&labeledExpr{
							pos:   position{line: 74, col: 55, offset: 1417},
							label: "params",
							expr: &zeroOrOneExpr{
								pos: position{line: 74, col: 62, offset: 1424},
								expr: &ruleRefExpr{
									pos:  position{line: 74, col: 62, offset: 1424},
									name: "ParameterList",
								},
							},
						},
						&litMatcher{
							pos:        position{line: 74, col: 77, offset: 1439},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
						&ruleRefExpr{
							pos:  position{line: 74, col: 81, offset: 1443},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 74, col: 83, offset: 1445},
							label: "ret",
							expr: &zeroOrOneExpr{
								pos: position{line: 74, col: 87, offset: 1449},
								expr: &ruleRefExpr{
									pos:  position{line: 74, col: 87, offset: 1449},
									name: "Type",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 74, col: 93, offset: 1455},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 74, col: 95, offset: 1457},
							val:        "{",
							ignoreCase: false,
							want:       "\"{\"",
						},
						&labeledExpr{
							pos:   position{line: 74, col: 99, offset: 1461},
							label: "body",
							expr: &zeroOrMoreExpr{
								pos: position{line: 74, col: 104, offset: 1466},
								expr: &ruleRefExpr{
									pos:  position{line: 74, col: 105, offset: 1467},
									name: "Statement",
								},
							},
						},
						&litMatcher{
							pos:        position{line: 74, col: 117, offset: 1479},
							val:        "}",
							ignoreCase: false,
							want:       "\"}\"",
						},
						&ruleRefExpr{
							pos:  position{line: 74, col: 121, offset: 1483},
							name: "_",
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "ParameterList",
			pos:  position{line: 92, col: 1, offset: 1744},
			expr: &actionExpr{
				pos: position{line: 92, col: 18, offset: 1761},
				run: (*parser).callonParameterList1,
				expr: &seqExpr{
					pos: position{line: 92, col: 18, offset: 1761},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 92, col: 18, offset: 1761},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 92, col: 20, offset: 1763},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 92, col: 25, offset: 1768},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 92, col: 36, offset: 1779},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 92, col: 38, offset: 1781},
							label: "typ",
							expr: &ruleRefExpr{
								pos:  position{line: 92, col: 42, offset: 1785},
								name: "Type",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 92, col: 47, offset: 1790},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 92, col: 49, offset: 1792},
							label: "rest",
							expr: &zeroOrOneExpr{
								pos: position{line: 92, col: 54, offset: 1797},
								expr: &ruleRefExpr{
									pos:  position{line: 92, col: 54, offset: 1797},
									name: "ParameterListComma",
								},
							},
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "ParameterListComma",
			pos:  position{line: 105, col: 1, offset: 2012},
			expr: &actionExpr{
				pos: position{line: 105, col: 23, offset: 2034},
				run: (*parser).callonParameterListComma1,
				expr: &seqExpr{
					pos: position{line: 105, col: 23, offset: 2034},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 105, col: 23, offset: 2034},
							val:        ",",
							ignoreCase: false,
							want:       "\",\"",
						},
						&labeledExpr{
							pos:   position{line: 105, col: 27, offset: 2038},
							label: "rest",
							expr: &ruleRefExpr{
								pos:  position{line: 105, col: 32, offset: 2043},
								name: "ParameterList",
							},
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "Identifier",
			pos:  position{line: 109, col: 1, offset: 2081},
			expr: &actionExpr{
				pos: position{line: 109, col: 15, offset: 2095},
				run: (*parser).callonIdentifier1,
				expr: &seqExpr{
					pos: position{line: 109, col: 15, offset: 2095},
					exprs: []any{
						&charClassMatcher{
							pos:        position{line: 109, col: 15, offset: 2095},
							val:        "[_a-zA-Z]",
							chars:      []rune{'_'},
							ranges:     []rune{'a', 'z', 'A', 'Z'},
							ignoreCase: false,
							inverted:   false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 109, col: 24, offset: 2104},
							expr: &charClassMatcher{
								pos:        position{line: 109, col: 24, offset: 2104},
								val:        "[_a-zA-Z0-9]",
								chars:      []rune{'_'},
								ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "Expr",
			pos:  position{line: 113, col: 1, offset: 2156},
			expr: &choiceExpr{
				pos: position{line: 113, col: 9, offset: 2164},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 113, col: 9, offset: 2164},
						name: "CallExpr",
					},
					&ruleRefExpr{
						pos:  position{line: 113, col: 20, offset: 2175},
						name: "DotExpr",
					},
					&ruleRefExpr{
						pos:  position{line: 113, col: 30, offset: 2185},
						name: "BinaryExpr",
					},
					&ruleRefExpr{
						pos:  position{line: 113, col: 43, offset: 2198},
						name: "NumberLiteral",
					},
					&ruleRefExpr{
						pos:  position{line: 113, col: 59, offset: 2214},
						name: "StringLiteral",
					},
					&ruleRefExpr{
						pos:  position{line: 113, col: 75, offset: 2230},
						name: "BooleanLiteral",
					},
					&ruleRefExpr{
						pos:  position{line: 113, col: 92, offset: 2247},
						name: "IdentifierExpr",
					},
				},
			},
			leader:        true,
			leftRecursive: true,
		},
		{
			name: "NumberLiteral",
			pos:  position{line: 115, col: 1, offset: 2263},
			expr: &actionExpr{
				pos: position{line: 115, col: 18, offset: 2280},
				run: (*parser).callonNumberLiteral1,
				expr: &seqExpr{
					pos: position{line: 115, col: 18, offset: 2280},
					exprs: []any{
						&zeroOrOneExpr{
							pos: position{line: 115, col: 18, offset: 2280},
							expr: &litMatcher{
								pos:        position{line: 115, col: 18, offset: 2280},
								val:        "-",
								ignoreCase: false,
								want:       "\"-\"",
							},
						},
						&choiceExpr{
							pos: position{line: 115, col: 26, offset: 2288},
							alternatives: []any{
								&oneOrMoreExpr{
									pos: position{line: 115, col: 26, offset: 2288},
									expr: &charClassMatcher{
										pos:        position{line: 115, col: 26, offset: 2288},
										val:        "[0-9]",
										ranges:     []rune{'0', '9'},
										ignoreCase: false,
										inverted:   false,
									},
								},
								&seqExpr{
									pos: position{line: 115, col: 35, offset: 2297},
									exprs: []any{
										&oneOrMoreExpr{
											pos: position{line: 115, col: 35, offset: 2297},
											expr: &charClassMatcher{
												pos:        position{line: 115, col: 35, offset: 2297},
												val:        "[0-9]",
												ranges:     []rune{'0', '9'},
												ignoreCase: false,
												inverted:   false,
											},
										},
										&anyMatcher{
											line: 115, col: 41, offset: 2303,
										},
										&oneOrMoreExpr{
											pos: position{line: 115, col: 42, offset: 2304},
											expr: &charClassMatcher{
												pos:        position{line: 115, col: 42, offset: 2304},
												val:        "[0-9]",
												ranges:     []rune{'0', '9'},
												ignoreCase: false,
												inverted:   false,
											},
										},
									},
								},
							},
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "StringLiteral",
			pos:  position{line: 124, col: 1, offset: 2440},
			expr: &actionExpr{
				pos: position{line: 124, col: 18, offset: 2457},
				run: (*parser).callonStringLiteral1,
				expr: &seqExpr{
					pos: position{line: 124, col: 18, offset: 2457},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 124, col: 18, offset: 2457},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
						&zeroOrMoreExpr{
							pos: position{line: 124, col: 22, offset: 2461},
							expr: &choiceExpr{
								pos: position{line: 124, col: 24, offset: 2463},
								alternatives: []any{
									&seqExpr{
										pos: position{line: 124, col: 24, offset: 2463},
										exprs: []any{
											&notExpr{
												pos: position{line: 124, col: 24, offset: 2463},
												expr: &ruleRefExpr{
													pos:  position{line: 124, col: 25, offset: 2464},
													name: "EscapedChar",
												},
											},
											&anyMatcher{
												line: 124, col: 37, offset: 2476,
											},
										},
									},
									&seqExpr{
										pos: position{line: 124, col: 41, offset: 2480},
										exprs: []any{
											&litMatcher{
												pos:        position{line: 124, col: 41, offset: 2480},
												val:        "\\",
												ignoreCase: false,
												want:       "\"\\\\\"",
											},
											&ruleRefExpr{
												pos:  position{line: 124, col: 46, offset: 2485},
												name: "EscapeSequence",
											},
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 124, col: 64, offset: 2503},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "BooleanLiteral",
			pos:  position{line: 134, col: 1, offset: 2710},
			expr: &actionExpr{
				pos: position{line: 134, col: 19, offset: 2728},
				run: (*parser).callonBooleanLiteral1,
				expr: &choiceExpr{
					pos: position{line: 134, col: 20, offset: 2729},
					alternatives: []any{
						&litMatcher{
							pos:        position{line: 134, col: 20, offset: 2729},
							val:        "true",
							ignoreCase: false,
							want:       "\"true\"",
						},
						&litMatcher{
							pos:        position{line: 134, col: 29, offset: 2738},
							val:        "false",
							ignoreCase: false,
							want:       "\"false\"",
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "IdentifierExpr",
			pos:  position{line: 138, col: 1, offset: 2805},
			expr: &actionExpr{
				pos: position{line: 138, col: 19, offset: 2823},
				run: (*parser).callonIdentifierExpr1,
				expr: &labeledExpr{
					pos:   position{line: 138, col: 19, offset: 2823},
					label: "ident",
					expr: &ruleRefExpr{
						pos:  position{line: 138, col: 25, offset: 2829},
						name: "Identifier",
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "CallExpr",
			pos:  position{line: 142, col: 1, offset: 2906},
			expr: &actionExpr{
				pos: position{line: 142, col: 13, offset: 2918},
				run: (*parser).callonCallExpr1,
				expr: &seqExpr{
					pos: position{line: 142, col: 13, offset: 2918},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 142, col: 13, offset: 2918},
							label: "exp",
							expr: &ruleRefExpr{
								pos:  position{line: 142, col: 17, offset: 2922},
								name: "Expr",
							},
						},
						&litMatcher{
							pos:        position{line: 142, col: 22, offset: 2927},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&labeledExpr{
							pos:   position{line: 142, col: 26, offset: 2931},
							label: "args",
							expr: &zeroOrOneExpr{
								pos: position{line: 142, col: 31, offset: 2936},
								expr: &ruleRefExpr{
									pos:  position{line: 142, col: 31, offset: 2936},
									name: "CallArgumentList",
								},
							},
						},
						&litMatcher{
							pos:        position{line: 142, col: 49, offset: 2954},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
			leader:        false,
			leftRecursive: true,
		},
		{
			name: "CallArgumentList",
			pos:  position{line: 154, col: 1, offset: 3083},
			expr: &actionExpr{
				pos: position{line: 154, col: 21, offset: 3103},
				run: (*parser).callonCallArgumentList1,
				expr: &seqExpr{
					pos: position{line: 154, col: 21, offset: 3103},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 154, col: 21, offset: 3103},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 154, col: 23, offset: 3105},
							label: "exp",
							expr: &ruleRefExpr{
								pos:  position{line: 154, col: 27, offset: 3109},
								name: "Expr",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 154, col: 32, offset: 3114},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 154, col: 34, offset: 3116},
							label: "rest",
							expr: &zeroOrOneExpr{
								pos: position{line: 154, col: 39, offset: 3121},
								expr: &ruleRefExpr{
									pos:  position{line: 154, col: 39, offset: 3121},
									name: "CallArgumentListComma",
								},
							},
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "CallArgumentListComma",
			pos:  position{line: 162, col: 1, offset: 3267},
			expr: &actionExpr{
				pos: position{line: 162, col: 26, offset: 3292},
				run: (*parser).callonCallArgumentListComma1,
				expr: &seqExpr{
					pos: position{line: 162, col: 26, offset: 3292},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 162, col: 26, offset: 3292},
							val:        ",",
							ignoreCase: false,
							want:       "\",\"",
						},
						&labeledExpr{
							pos:   position{line: 162, col: 30, offset: 3296},
							label: "rest",
							expr: &ruleRefExpr{
								pos:  position{line: 162, col: 35, offset: 3301},
								name: "CallArgumentList",
							},
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "DotExpr",
			pos:  position{line: 166, col: 1, offset: 3342},
			expr: &actionExpr{
				pos: position{line: 166, col: 12, offset: 3353},
				run: (*parser).callonDotExpr1,
				expr: &seqExpr{
					pos: position{line: 166, col: 12, offset: 3353},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 166, col: 12, offset: 3353},
							label: "exp",
							expr: &ruleRefExpr{
								pos:  position{line: 166, col: 16, offset: 3357},
								name: "Expr",
							},
						},
						&litMatcher{
							pos:        position{line: 166, col: 21, offset: 3362},
							val:        ".",
							ignoreCase: false,
							want:       "\".\"",
						},
						&labeledExpr{
							pos:   position{line: 166, col: 25, offset: 3366},
							label: "ident",
							expr: &ruleRefExpr{
								pos:  position{line: 166, col: 31, offset: 3372},
								name: "Identifier",
							},
						},
					},
				},
			},
			leader:        false,
			leftRecursive: true,
		},
		{
			name: "BinaryExpr",
			pos:  position{line: 173, col: 1, offset: 3464},
			expr: &choiceExpr{
				pos: position{line: 173, col: 15, offset: 3478},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 173, col: 15, offset: 3478},
						run: (*parser).callonBinaryExpr2,
						expr: &seqExpr{
							pos: position{line: 173, col: 15, offset: 3478},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 173, col: 15, offset: 3478},
									label: "left",
									expr: &ruleRefExpr{
										pos:  position{line: 173, col: 20, offset: 3483},
										name: "Expr",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 173, col: 25, offset: 3488},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 173, col: 27, offset: 3490},
									label: "op",
									expr: &litMatcher{
										pos:        position{line: 173, col: 31, offset: 3494},
										val:        "**",
										ignoreCase: false,
										want:       "\"**\"",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 173, col: 37, offset: 3500},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 173, col: 39, offset: 3502},
									label: "right",
									expr: &ruleRefExpr{
										pos:  position{line: 173, col: 45, offset: 3508},
										name: "Expr",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 179, col: 5, offset: 3634},
						run: (*parser).callonBinaryExpr12,
						expr: &seqExpr{
							pos: position{line: 179, col: 5, offset: 3634},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 179, col: 5, offset: 3634},
									label: "left",
									expr: &ruleRefExpr{
										pos:  position{line: 179, col: 10, offset: 3639},
										name: "Expr",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 179, col: 15, offset: 3644},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 179, col: 17, offset: 3646},
									label: "op",
									expr: &choiceExpr{
										pos: position{line: 179, col: 21, offset: 3650},
										alternatives: []any{
											&litMatcher{
												pos:        position{line: 179, col: 21, offset: 3650},
												val:        "*",
												ignoreCase: false,
												want:       "\"*\"",
											},
											&litMatcher{
												pos:        position{line: 179, col: 27, offset: 3656},
												val:        "/",
												ignoreCase: false,
												want:       "\"/\"",
											},
											&litMatcher{
												pos:        position{line: 179, col: 33, offset: 3662},
												val:        "%",
												ignoreCase: false,
												want:       "\"%\"",
											},
											&litMatcher{
												pos:        position{line: 179, col: 39, offset: 3668},
												val:        "<<",
												ignoreCase: false,
												want:       "\"<<\"",
											},
											&litMatcher{
												pos:        position{line: 179, col: 46, offset: 3675},
												val:        ">>",
												ignoreCase: false,
												want:       "\">>\"",
											},
											&litMatcher{
												pos:        position{line: 179, col: 53, offset: 3682},
												val:        "&",
												ignoreCase: false,
												want:       "\"&\"",
											},
										},
									},
								},
								&ruleRefExpr{
									pos:  position{line: 179, col: 58, offset: 3687},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 179, col: 60, offset: 3689},
									label: "right",
									expr: &ruleRefExpr{
										pos:  position{line: 179, col: 66, offset: 3695},
										name: "Expr",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 185, col: 5, offset: 3821},
						run: (*parser).callonBinaryExpr28,
						expr: &seqExpr{
							pos: position{line: 185, col: 5, offset: 3821},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 185, col: 5, offset: 3821},
									label: "left",
									expr: &ruleRefExpr{
										pos:  position{line: 185, col: 10, offset: 3826},
										name: "Expr",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 185, col: 15, offset: 3831},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 185, col: 17, offset: 3833},
									label: "op",
									expr: &choiceExpr{
										pos: position{line: 185, col: 21, offset: 3837},
										alternatives: []any{
											&litMatcher{
												pos:        position{line: 185, col: 21, offset: 3837},
												val:        "+",
												ignoreCase: false,
												want:       "\"+\"",
											},
											&litMatcher{
												pos:        position{line: 185, col: 27, offset: 3843},
												val:        "-",
												ignoreCase: false,
												want:       "\"-\"",
											},
											&litMatcher{
												pos:        position{line: 185, col: 33, offset: 3849},
												val:        "|",
												ignoreCase: false,
												want:       "\"|\"",
											},
											&litMatcher{
												pos:        position{line: 185, col: 39, offset: 3855},
												val:        "^",
												ignoreCase: false,
												want:       "\"^\"",
											},
										},
									},
								},
								&ruleRefExpr{
									pos:  position{line: 185, col: 44, offset: 3860},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 185, col: 46, offset: 3862},
									label: "right",
									expr: &ruleRefExpr{
										pos:  position{line: 185, col: 52, offset: 3868},
										name: "Expr",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 191, col: 5, offset: 3994},
						run: (*parser).callonBinaryExpr42,
						expr: &seqExpr{
							pos: position{line: 191, col: 5, offset: 3994},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 191, col: 5, offset: 3994},
									label: "left",
									expr: &ruleRefExpr{
										pos:  position{line: 191, col: 10, offset: 3999},
										name: "Expr",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 191, col: 15, offset: 4004},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 191, col: 17, offset: 4006},
									label: "op",
									expr: &choiceExpr{
										pos: position{line: 191, col: 21, offset: 4010},
										alternatives: []any{
											&litMatcher{
												pos:        position{line: 191, col: 21, offset: 4010},
												val:        "==",
												ignoreCase: false,
												want:       "\"==\"",
											},
											&litMatcher{
												pos:        position{line: 191, col: 28, offset: 4017},
												val:        "!=",
												ignoreCase: false,
												want:       "\"!=\"",
											},
											&litMatcher{
												pos:        position{line: 191, col: 35, offset: 4024},
												val:        "<",
												ignoreCase: false,
												want:       "\"<\"",
											},
											&litMatcher{
												pos:        position{line: 191, col: 41, offset: 4030},
												val:        ">",
												ignoreCase: false,
												want:       "\">\"",
											},
											&litMatcher{
												pos:        position{line: 191, col: 47, offset: 4036},
												val:        ">=",
												ignoreCase: false,
												want:       "\">=\"",
											},
											&litMatcher{
												pos:        position{line: 191, col: 54, offset: 4043},
												val:        "<=",
												ignoreCase: false,
												want:       "\"<=\"",
											},
										},
									},
								},
								&ruleRefExpr{
									pos:  position{line: 191, col: 60, offset: 4049},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 191, col: 62, offset: 4051},
									label: "right",
									expr: &ruleRefExpr{
										pos:  position{line: 191, col: 68, offset: 4057},
										name: "Expr",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 197, col: 5, offset: 4183},
						run: (*parser).callonBinaryExpr58,
						expr: &seqExpr{
							pos: position{line: 197, col: 5, offset: 4183},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 197, col: 5, offset: 4183},
									label: "left",
									expr: &ruleRefExpr{
										pos:  position{line: 197, col: 10, offset: 4188},
										name: "Expr",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 197, col: 15, offset: 4193},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 197, col: 17, offset: 4195},
									label: "op",
									expr: &litMatcher{
										pos:        position{line: 197, col: 21, offset: 4199},
										val:        "&&",
										ignoreCase: false,
										want:       "\"&&\"",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 197, col: 27, offset: 4205},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 197, col: 29, offset: 4207},
									label: "right",
									expr: &ruleRefExpr{
										pos:  position{line: 197, col: 35, offset: 4213},
										name: "Expr",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 203, col: 5, offset: 4339},
						run: (*parser).callonBinaryExpr68,
						expr: &seqExpr{
							pos: position{line: 203, col: 5, offset: 4339},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 203, col: 5, offset: 4339},
									label: "left",
									expr: &ruleRefExpr{
										pos:  position{line: 203, col: 10, offset: 4344},
										name: "Expr",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 203, col: 15, offset: 4349},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 203, col: 17, offset: 4351},
									label: "op",
									expr: &litMatcher{
										pos:        position{line: 203, col: 21, offset: 4355},
										val:        "||",
										ignoreCase: false,
										want:       "\"||\"",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 203, col: 27, offset: 4361},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 203, col: 29, offset: 4363},
									label: "right",
									expr: &ruleRefExpr{
										pos:  position{line: 203, col: 35, offset: 4369},
										name: "Expr",
									},
								},
							},
						},
					},
				},
			},
			leader:        false,
			leftRecursive: true,
		},
		{
			name: "EscapedChar",
			pos:  position{line: 211, col: 1, offset: 4494},
			expr: &charClassMatcher{
				pos:        position{line: 211, col: 16, offset: 4509},
				val:        "[\\x00-\\x1f\"\\\\]",
				chars:      []rune{'"', '\\'},
				ranges:     []rune{'\x00', '\x1f'},
				ignoreCase: false,
				inverted:   false,
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "EscapeSequence",
			pos:  position{line: 213, col: 1, offset: 4525},
			expr: &choiceExpr{
				pos: position{line: 213, col: 19, offset: 4543},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 213, col: 19, offset: 4543},
						name: "SingleCharEscape",
					},
					&ruleRefExpr{
						pos:  position{line: 213, col: 38, offset: 4562},
						name: "UnicodeEscape",
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "SingleCharEscape",
			pos:  position{line: 215, col: 1, offset: 4577},
			expr: &charClassMatcher{
				pos:        position{line: 215, col: 21, offset: 4597},
				val:        "[\"\\\\/bfnrt]",
				chars:      []rune{'"', '\\', '/', 'b', 'f', 'n', 'r', 't'},
				ignoreCase: false,
				inverted:   false,
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 217, col: 1, offset: 4610},
			expr: &zeroOrMoreExpr{
				pos: position{line: 217, col: 19, offset: 4628},
				expr: &charClassMatcher{
					pos:        position{line: 217, col: 19, offset: 4628},
					val:        "[ \\n\\t\\r]",
					chars:      []rune{' ', '\n', '\t', '\r'},
					ignoreCase: false,
					inverted:   false,
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "EOF",
			pos:  position{line: 219, col: 1, offset: 4640},
			expr: &notExpr{
				pos: position{line: 219, col: 8, offset: 4647},
				expr: &anyMatcher{
					line: 219, col: 9, offset: 4648,
				},
			},
			leader:        false,
			leftRecursive: false,
		},
	},
}

func (c *current) onProgram1(pkg, decls any) (any, error) {
	return Program{
		Package: pkg.(Package),

		Declarations: anyToSlice[Declaration](decls),
	}, nil
}

func (p *parser) callonProgram1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onProgram1(stack["pkg"], stack["decls"])
}

func (c *current) onPackage1(name any) (any, error) {
	return Package{
		Name: name.(Identifier),
	}, nil
}

func (p *parser) callonPackage1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPackage1(stack["name"])
}

func (c *current) onPointerType1(pointee any) (any, error) {
	return PointerType{Pointee: pointee.(Type)}, nil
}

func (p *parser) callonPointerType1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPointerType1(stack["pointee"])
}

func (c *current) onVarStatement1(name, typ, exp any) (any, error) {
	var v VarStatement
	v.Name = name.(Identifier)
	if typ != nil {
		typePtr := typ.(Type)
		v.Type = &typePtr
	}

	if exp != nil {
		expPtr := exp.(Expr)
		v.Expr = &expPtr
	}

	if typ == nil && exp == nil {
		return nil, fmt.Errorf("var statement must have a type or an expression")
	}

	return v, nil
}

func (p *parser) callonVarStatement1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVarStatement1(stack["name"], stack["typ"], stack["exp"])
}

func (c *current) onVarStatementExpr1(exp any) (any, error) {
	return exp.(Expr), nil
}

func (p *parser) callonVarStatementExpr1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVarStatementExpr1(stack["exp"])
}

func (c *current) onExprStatement1(exp any) (any, error) {
	return ExprStatement{Expr: exp.(Expr)}, nil
}

func (p *parser) callonExprStatement1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExprStatement1(stack["exp"])
}

func (c *current) onPostfixStatement1(exp, op any) (any, error) {
	return PostfixStatement{Expr: exp.(Expr), Operator: Operator(op.([]byte))}, nil
}

func (p *parser) callonPostfixStatement1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPostfixStatement1(stack["exp"], stack["op"])
}

func (c *current) onFunctionDeclaration1(name, params, ret, body any) (any, error) {
	f := FunctionDeclaration{
		Name: name.(Identifier),
		Body: anyToSlice[Statement](body),
	}

	if params != nil {
		f.Parameters = params.([]Parameter)
	}

	if ret != nil {
		retPtr := ret.(Type)
		f.Return = &retPtr
	}

	return f, nil
}

func (p *parser) callonFunctionDeclaration1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFunctionDeclaration1(stack["name"], stack["params"], stack["ret"], stack["body"])
}

func (c *current) onParameterList1(name, typ, rest any) (any, error) {
	p := Parameter{
		Name: name.(Identifier),
		Type: typ.(Type),
	}

	if rest == nil {
		return []Parameter{p}, nil
	}

	return append([]Parameter{p}, rest.([]Parameter)...), nil
}

func (p *parser) callonParameterList1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onParameterList1(stack["name"], stack["typ"], stack["rest"])
}

func (c *current) onParameterListComma1(rest any) (any, error) {
	return rest, nil
}

func (p *parser) callonParameterListComma1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onParameterListComma1(stack["rest"])
}

func (c *current) onIdentifier1() (any, error) {
	return Identifier(c.text), nil
}

func (p *parser) callonIdentifier1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdentifier1()
}

func (c *current) onNumberLiteral1() (any, error) {
	f, err := strconv.ParseFloat(string(c.text), 64)
	if err != nil {
		return 0, err
	}

	return NumberLiteral(f), nil
}

func (p *parser) callonNumberLiteral1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumberLiteral1()
}

func (c *current) onStringLiteral1() (any, error) {
	c.text = bytes.Replace(c.text, []byte(`\/`), []byte(`/`), -1)
	str, err := strconv.Unquote(string(c.text))
	if err != nil {
		return nil, err
	}

	return StringLiteral(str), nil
}

func (p *parser) callonStringLiteral1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStringLiteral1()
}

func (c *current) onBooleanLiteral1() (any, error) {
	return BooleanLiteral(string(c.text) == "true"), nil
}

func (p *parser) callonBooleanLiteral1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBooleanLiteral1()
}

func (c *current) onIdentifierExpr1(ident any) (any, error) {
	return IdentifierExpr{Identifier: ident.(Identifier)}, nil
}

func (p *parser) callonIdentifierExpr1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdentifierExpr1(stack["ident"])
}

func (c *current) onCallExpr1(exp, args any) (any, error) {
	call := CallExpr{
		Expr: exp.(Expr),
	}

	if args != nil {
		call.Args = args.([]Expr)
	}

	return call, nil
}

func (p *parser) callonCallExpr1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCallExpr1(stack["exp"], stack["args"])
}

func (c *current) onCallArgumentList1(exp, rest any) (any, error) {
	if rest != nil {
		return append([]Expr{exp.(Expr)}, rest.([]Expr)...), nil
	}

	return []Expr{exp.(Expr)}, nil
}

func (p *parser) callonCallArgumentList1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCallArgumentList1(stack["exp"], stack["rest"])
}

func (c *current) onCallArgumentListComma1(rest any) (any, error) {
	return rest, nil
}

func (p *parser) callonCallArgumentListComma1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCallArgumentListComma1(stack["rest"])
}

func (c *current) onDotExpr1(exp, ident any) (any, error) {
	return DotExpr{
		Expr: exp.(Expr),
		Key:  ident.(Identifier),
	}, nil
}

func (p *parser) callonDotExpr1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDotExpr1(stack["exp"], stack["ident"])
}

func (c *current) onBinaryExpr2(left, op, right any) (any, error) {
	return BinaryExpr{
		Left:     left.(Expr),
		Operator: Operator(op.([]byte)),
		Right:    right.(Expr),
	}, nil
}

func (p *parser) callonBinaryExpr2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBinaryExpr2(stack["left"], stack["op"], stack["right"])
}

func (c *current) onBinaryExpr12(left, op, right any) (any, error) {
	return BinaryExpr{
		Left:     left.(Expr),
		Operator: Operator(op.([]byte)),
		Right:    right.(Expr),
	}, nil
}

func (p *parser) callonBinaryExpr12() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBinaryExpr12(stack["left"], stack["op"], stack["right"])
}

func (c *current) onBinaryExpr28(left, op, right any) (any, error) {
	return BinaryExpr{
		Left:     left.(Expr),
		Operator: Operator(op.([]byte)),
		Right:    right.(Expr),
	}, nil
}

func (p *parser) callonBinaryExpr28() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBinaryExpr28(stack["left"], stack["op"], stack["right"])
}

func (c *current) onBinaryExpr42(left, op, right any) (any, error) {
	return BinaryExpr{
		Left:     left.(Expr),
		Operator: Operator(op.([]byte)),
		Right:    right.(Expr),
	}, nil
}

func (p *parser) callonBinaryExpr42() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBinaryExpr42(stack["left"], stack["op"], stack["right"])
}

func (c *current) onBinaryExpr58(left, op, right any) (any, error) {
	return BinaryExpr{
		Left:     left.(Expr),
		Operator: Operator(op.([]byte)),
		Right:    right.(Expr),
	}, nil
}

func (p *parser) callonBinaryExpr58() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBinaryExpr58(stack["left"], stack["op"], stack["right"])
}

func (c *current) onBinaryExpr68(left, op, right any) (any, error) {
	return BinaryExpr{
		Left:     left.(Expr),
		Operator: Operator(op.([]byte)),
		Right:    right.(Expr),
	}, nil
}

func (p *parser) callonBinaryExpr68() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBinaryExpr68(stack["left"], stack["op"], stack["right"])
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any

	leader        bool
	leftRecursive bool
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type ruleWithExpsStack struct {
	rule   *rule
	estack []any
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleRecursiveLeader(rule *rule) (any, bool) {
	result, ok := p.getMemoized(rule)
	if ok {
		p.restore(result.end)
		return result.v, result.b
	}

	if p.debug {
		defer p.out(p.in("recursive " + rule.name))
	}

	var (
		depth      = 0
		startMark  = p.pt
		lastResult = resultTuple{nil, false, startMark}
		lastErrors = *p.errs
	)

	for {
		lastState := p.cloneState()
		p.setMemoized(startMark, rule, lastResult)
		val, ok := p.parseRule(rule)
		endMark := p.pt
		if p.debug {
			p.printIndent("RECURSIVE", fmt.Sprintf(
				"Rule %s depth %d: %t -> %s",
				rule.name, depth, ok, string(p.sliceFrom(startMark))))
		}
		if (!ok) || (endMark.offset <= lastResult.end.offset && depth != 0) {
			p.restoreState(lastState)
			*p.errs = lastErrors
			break
		}
		lastResult = resultTuple{val, ok, endMark}
		lastErrors = *p.errs
		p.restore(startMark)
		depth++
	}

	p.restore(lastResult.end)
	p.setMemoized(startMark, rule, lastResult)
	return lastResult.v, lastResult.b
}

func (p *parser) parseRuleRecursiveNoLeader(rule *rule) (any, bool) {
	return p.parseRule(rule)
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize || rule.leftRecursive {
		if rule.leader {
			val, ok = p.parseRuleRecursiveLeader(rule)
		} else if p.memoize && !rule.leftRecursive {
			val, ok = p.parseRuleMemoize(rule)
		} else {
			val, ok = p.parseRuleRecursiveNoLeader(rule)
		}
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	isLeftRecusion := p.rstack[len(p.rstack)-1].leftRecursive
	if p.memoize && !isLeftRecusion {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize && !isLeftRecusion {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
